export default {
  layout: {
    name: "klay",
    nodeDimensionsIncludeLabels: true,
    klay: {
      direction: "RIGHT",
      borderSpacing: 100,
      spacing: 30,
    },
  },
  wheelSensitivity: 0.25,
  style: [
    {
      selector: "node",
      style: {
        label: "data(label)",
        width: "500px",
        "font-family": "Avenir, Helvetica, Arial, sans-serif",
        "font-size": "2em",
      },
    },
    {
      selector: "edge",
      css: {
        "curve-style": "taxi",
        "line-fill": "linear-gradient",
        "line-gradient-stop-colors": "data(gradient)",
        "line-dash-offset": 24,
        width: 10,
      },
    },
    {
      selector: ".basename",
      style: {
        padding: "200px",
        "text-margin-y": 75,
        "font-weight": "bold",
        shape: "roundrectangle",
        "min-height": "400px",
        "border-width": 2,
        "border-color": "white",
        "background-color": "#f4ecff",
      },
    },
    {
      selector: ".fname",
      style: {
        padding: "100px",
        "text-margin-y": 75,
        "font-weight": "bold",
        shape: "roundrectangle",
        "border-width": 1,
        "border-color": "lightgrey",
        "background-color": "white",
      },
    },
    {
      selector: ".provider",
      style: {
        "text-valign": "center",
        "text-halign": "center",
        padding: "1em",
        shape: "roundrectangle",
        "border-width": 0,
        color: "white",
        "background-color": "black",
      },
    },
    {
      selector: ".module",
      style: {
        padding: "100px",
        "font-weight": "bold",
        "text-margin-y": 60,
        shape: "roundrectangle",
        color: "#8450ba",
        "border-width": 10,
        "border-color": "#8450ba",
        "background-color": "white",
      },
    },
    {
      selector: ".data-type",
      style: {
        padding: "10%",
        // width: "label",
        "font-weight": "bold",
        "text-background-color": "white",
        "text-background-opacity": 1,
        "text-background-padding": "2em",
        "text-margin-y": 15,
        shape: "roundrectangle",
        "border-width": "5px",
        "border-color": "black",
        "background-color": "white",
        // "text-background-color": "data(parentColor)",
        // "background-color": "data(parentColor)",
      },
    },
    {
      selector: ".data-name",
      css: {
        "background-color": "#ffecec",
        color: "black",
        "font-weight": "bold",
        "text-valign": "center",
        "text-halign": "center",
        padding: "1.5em",
        shape: "roundrectangle",
        "border-opacity": 1,
        "border-width": 5,
        "border-color": "#dc477d",
        label: "data(label)",
      },
    },
    {
      selector: ".output",
      css: {
        "background-color": "#fff7e0",
        color: "black",
        "font-weight": "bold",
        "text-valign": "center",
        "text-halign": "center",
        padding: "1.5em",
        shape: "roundrectangle",
        "border-opacity": 1,
        "border-width": 5,
        "border-color": "#ffc107",
        label: "data(label)",
      },
    },
    {
      selector: ".variable",
      css: {
        "background-color": "#e1f0ff",
        color: "black",
        "font-weight": "bold",
        "text-valign": "center",
        "text-halign": "center",
        padding: "1.5em",
        shape: "roundrectangle",
        "border-opacity": 1,
        "border-width": 5,
        "border-color": "#1d7ada",
        label: "data(label)",
      },
    },
    {
      selector: ".locals",
      css: {
        "background-color": "black",
        color: "white",
        "font-weight": "bold",
        "text-valign": "center",
        "text-halign": "center",
        padding: "1.5em",
        shape: "roundrectangle",
        "border-opacity": 1,
        "border-width": 5,
        "border-color": "black",
        label: "data(label)",
      },
    },
    {
      selector: ".resource-type",
      style: {
        padding: "10%",
        // width: "label",
        "font-weight": "bold",
        "text-background-color": "white",
        "text-background-opacity": 1,
        "text-background-padding": "2em",
        "text-margin-y": 15,
        shape: "roundrectangle",
        "border-width": "5px",
        "border-color": "black",
        "background-color": "white",
        // "text-background-color": "data(parentColor)",
        // "background-color": "data(parentColor)",
      },
    },
    {
      selector: ".resource-parent",
      style: {
        padding: "10%",
        // width: "label",
        "font-weight": "bold",
        "text-background-color": "white",
        "text-background-opacity": 1,
        "text-background-padding": "2em",
        "text-margin-y": 15,
        shape: "roundrectangle",
        "border-width": "5px",
        "border-color": "black",
        "background-color": "white",
        // "text-background-color": "data(parentColor)",
        // "background-color": "data(parentColor)",
      },
    },
    {
      selector: ".resource-name",
      css: {
        "text-valign": "center",
        "text-halign": "center",
        padding: "1.5em",
        shape: "roundrectangle",
        "border-opacity": 0,
        color: "white",
        "background-color": "#8450ba",
        "text-wrap": "ellipsis",
        "text-max-width": 500,
      },
    },
    {
      selector: ".create",
      css: {
        "background-color": "#28a745",
        color: "white",
        "font-weight": "bold",
      },
    },
    {
      selector: ".delete",
      css: {
        "background-color": "#e40707",
        color: "white",
        "font-weight": "bold",
      },
    },
    {
      selector: ".update",
      css: {
        "background-color": "#1d7ada",
        color: "white",
        "font-weight": "bold",
      },
    },
    {
      selector: ".replace",
      css: {
        "background-color": "#ffc107",
        color: "black",
        "font-weight": "bold",
      },
    },
    {
      selector: ".no-op",
      css: {
        color: "black",
        "border-opacity": 1,
        "font-weight": "bold",
        "border-width": "5px",
        "border-color": "lightgray",
        "background-color": "white",
      },
    },
    {
      selector: ".invisible",
      css: {
        opacity: "0",
      },
    },
    {
      selector: ".semitransp",
      css: {
        opacity: "0.4",
      },
    },
    {
      selector: "edge.semitransp",
      css: {
        opacity: "0",
      },
    },
    {
      selector: ".visible",
      css: {
        opacity: "1",
      },
    },
    {
      selector: ".dashed",
      css: {
        "line-style": "dashed",
        "line-dash-pattern": [20, 20],
      },
    },
  ],
};
